import{a as h,S as p,i as n}from"./assets/vendor-b11e2a50.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))o(e);new MutationObserver(e=>{for(const r of e)if(r.type==="childList")for(const u of r.addedNodes)u.tagName==="LINK"&&u.rel==="modulepreload"&&o(u)}).observe(document,{childList:!0,subtree:!0});function i(e){const r={};return e.integrity&&(r.integrity=e.integrity),e.referrerPolicy&&(r.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?r.credentials="include":e.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function o(e){if(e.ep)return;e.ep=!0;const r=i(e);fetch(e.href,r)}})();const g="44002724-78e4880ab6dd2cf163db4493f",L="https://pixabay.com/api/";async function f(s,t=1,i=15){try{return(await h.get(L,{params:{key:g,q:s,image_tupe:"photo",orientation:"horizontal",safesearch:!0,page:t,perPage:i}})).data}catch(o){throw console.error("Error fetching images:",o),o}}function b(){document.querySelector(".gallery").innerHTML=""}function m(s){const t=document.querySelector(".gallery"),i=s.map(e=>`
      <div class="gallery-item">
      <a href="${e.largeImageURL}" class="gallery__link">
        <img src="${e.webformatURL}" alt="${e.tags}" loading="lazy" />
        </a>         
          <ul>
            <li><p>Likes: ${e.likes}</p></li>
            <li><p>Views: ${e.views}</p></li>
            <li><p>Comments: ${e.comments}</p></li>
            <li><p>Downloads: ${e.downloads}</p></li>
          </ul>
      </div>
  `).join("");t.insertAdjacentHTML("beforeend",i),new p(".gallery a",{}).refresh()}const y=document.querySelector("#search-form"),v=y.querySelector('input[name="searchQuery"]'),c=document.querySelector(".load-more"),d=document.querySelector(".loader");let a=1,l="";y.addEventListener("submit",w);c.addEventListener("click",S);async function w(s){if(s.preventDefault(),l=v.value.trim(),!l){n.error({title:"Error",message:"Search query cannot be empty!"});return}b(),a=1,c.classList.add("hidden"),d.classList.remove("hidden");try{const t=await f(l,a);t.hits.length===0?n.warning({title:"No Results",message:"No images found for your search query. Please try again!"}):(m(t.hits),t.totalHits>a*15&&c.classList.remove("hidden"))}catch{n.error({title:"Error",message:"Failed to fetch images. Please try again later."})}finally{d.classList.add("hidden")}}async function S(){a+=1,d.classList.remove("hidden");try{const s=await f(l,a);m(s.hits),s.totalHits<=a*15&&(c.classList.add("hidden"),n.info({title:"End of Results",message:"We're sorry, but you've reached the end of search results."}))}catch{n.error({title:"Error",message:"Failed to fetch images. Please try again later."})}finally{d.classList.add("hidden")}}
//# sourceMappingURL=commonHelpers.js.map
